# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VisitDetails(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, date: str=None, description: str=None, id: int=None, pet_id: int=None):  # noqa: E501
        """VisitDetails - a model defined in Swagger

        :param date: The date of this VisitDetails.  # noqa: E501
        :type date: str
        :param description: The description of this VisitDetails.  # noqa: E501
        :type description: str
        :param id: The id of this VisitDetails.  # noqa: E501
        :type id: int
        :param pet_id: The pet_id of this VisitDetails.  # noqa: E501
        :type pet_id: int
        """
        self.swagger_types = {
            'date': str,
            'description': str,
            'id': int,
            'pet_id': int
        }

        self.attribute_map = {
            'date': 'date',
            'description': 'description',
            'id': 'id',
            'pet_id': 'petId'
        }

        self._date = date
        self._description = description
        self._id = id
        self._pet_id = pet_id

    @classmethod
    def from_dict(cls, dikt) -> 'VisitDetails':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VisitDetails of this VisitDetails.  # noqa: E501
        :rtype: VisitDetails
        """
        return util.deserialize_model(dikt, cls)

    @property
    def date(self) -> str:
        """Gets the date of this VisitDetails.


        :return: The date of this VisitDetails.
        :rtype: str
        """
        return self._date

    @date.setter
    def date(self, date: str):
        """Sets the date of this VisitDetails.


        :param date: The date of this VisitDetails.
        :type date: str
        """

        self._date = date

    @property
    def description(self) -> str:
        """Gets the description of this VisitDetails.


        :return: The description of this VisitDetails.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this VisitDetails.


        :param description: The description of this VisitDetails.
        :type description: str
        """

        self._description = description

    @property
    def id(self) -> int:
        """Gets the id of this VisitDetails.


        :return: The id of this VisitDetails.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this VisitDetails.


        :param id: The id of this VisitDetails.
        :type id: int
        """

        self._id = id

    @property
    def pet_id(self) -> int:
        """Gets the pet_id of this VisitDetails.


        :return: The pet_id of this VisitDetails.
        :rtype: int
        """
        return self._pet_id

    @pet_id.setter
    def pet_id(self, pet_id: int):
        """Sets the pet_id of this VisitDetails.


        :param pet_id: The pet_id of this VisitDetails.
        :type pet_id: int
        """

        self._pet_id = pet_id
