/*
 * Customers Service Api Documentation
 *
 * Documentation automatically generated
 *
 * API version: 1.5.3
 * Contact: run2obtain@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PetType struct {

	Id int32 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`
}
