/*
 * Customers Service Api Documentation
 *
 * Documentation automatically generated
 *
 * API version: 1.5.3
 * Contact: run2obtain@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Owner struct {

	Address string `json:"address,omitempty"`

	City string `json:"city,omitempty"`

	FirstName string `json:"firstName,omitempty"`

	Id int32 `json:"id,omitempty"`

	LastName string `json:"lastName,omitempty"`

	Pets []Pet `json:"pets,omitempty"`

	Telephone string `json:"telephone,omitempty"`
}
