/*
 * Customers Service Api Documentation
 *
 * Documentation automatically generated
 *
 * API version: 1.5.3
 * Contact: run2obtain@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type PetRequest struct {

	BirthDate time.Time `json:"birthDate,omitempty"`

	Id int32 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	TypeId int32 `json:"typeId,omitempty"`
}
