/*
 * Customers Service Api Documentation
 *
 * Documentation automatically generated
 *
 * API version: 1.5.3
 * Contact: run2obtain@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"//",
		Index,
	},

	Route{
		"CreateOwnerUsingPOST",
		strings.ToUpper("Post"),
		"//owners",
		CreateOwnerUsingPOST,
	},

	Route{
		"FindAllUsingGET",
		strings.ToUpper("Get"),
		"//owners",
		FindAllUsingGET,
	},

	Route{
		"FindOwnerUsingGET",
		strings.ToUpper("Get"),
		"//owners/{ownerId}",
		FindOwnerUsingGET,
	},

	Route{
		"UpdateOwnerUsingPUT",
		strings.ToUpper("Put"),
		"//owners/{ownerId}",
		UpdateOwnerUsingPUT,
	},

	Route{
		"FindPetUsingGET",
		strings.ToUpper("Get"),
		"//owners/*/pets/{petId}",
		FindPetUsingGET,
	},

	Route{
		"GetPetTypesUsingGET",
		strings.ToUpper("Get"),
		"//petTypes",
		GetPetTypesUsingGET,
	},

	Route{
		"ProcessCreationFormUsingPOST",
		strings.ToUpper("Post"),
		"//owners/{ownerId}/pets",
		ProcessCreationFormUsingPOST,
	},

	Route{
		"ProcessUpdateFormUsingPUT",
		strings.ToUpper("Put"),
		"//owners/*/pets/{petId}",
		ProcessUpdateFormUsingPUT,
	},
}
